const React = require('react');
const Svg = ({ children, ...props }) => React.createElement('svg', props, children);
module.exports = Svg;
module.exports.default = Svg;
module.exports.SvgXml = () => null;
module.exports.SvgUri = () => null;
module.exports.Circle = 'Circle';
module.exports.Rect = 'Rect';
module.exports.Path = 'Path';
module.exports.Line = 'Line';
module.exports.G = 'G';
module.exports.Text = 'Text';
module.exports.Polygon = 'Polygon';
module.exports.Polyline = 'Polyline';
module.exports.Ellipse = 'Ellipse';
module.exports.Defs = 'Defs';
module.exports.ClipPath = 'ClipPath';
module.exports.LinearGradient = 'LinearGradient';
module.exports.RadialGradient = 'RadialGradient';
module.exports.Stop = 'Stop';
module.exports.Image = 'Image';
module.exports.Use = 'Use';
module.exports.Symbol = 'Symbol';
module.exports.TSpan = 'TSpan';
module.exports.Mask = 'Mask';
